object Libraries {
    object Versions {
        val androidCore_CoreKtx = " 1.8.0"
        val orgJetbrainsKotlin_KotlinBom = " 1.8.0"
        val androidxAppcompatAppcompat = " 1.6.1"
        val androidMaterial = " 1.10.0"
        val jUnit = " 4.13.2"
        val androidxTestExtJunit = " 1.1.5"
        val androidxTestEspressoEspressoCore = " 3.5.1"
        val rxjava3_version = "3.0.12"
        val rxjava3_rxandroid_version = "3.0.0"
        val joda_date_time_version = "2.9.4"
        val mockk_version = "1.12.4"
        val orgJetbrainsKotlin_KotlinXCoroutuinesTest = " 1.6.4"
        val androidxArchCore_CoreTesting = " 2.1.0"
        val androidxLifecycle_LifecycleRuntimeKtx = " 2.3.1"
        val androidxActivity_ActivityCompose = " 1.5.1"
        val androidxCompose_composeBOM = " 2022.10.00"
        val ioInsertKoin_KoinAndroid = " 3.0.1"
        val comFacebookFlipper_Flipper = " 0.225.0"
        val comFacebookSOLoader_SOLoader = " 0.10.5"
        val okhttp_version = " 4.11.0"
        val retrofit_version = " 2.9.0"
        val ioCoilKt_CoilCompose = " 2.4.0"
        val comGoogleCodeGson_Gson = " 2.10.1"
        val rxjava3_retrofitadapter_version = "2.9.0"
        val comSquareupMoshi_MoshiKotlin = " 1.15.0"
        val comSquareupMoshi_MoshiAdapters = " 1.15.0"
        val comSquareupRetrofit2_ConverterMoshi = " 2.9.0"
    }
}

object ApiDependencies {
    val android_core_core_ktx = "androidx.core:core-ktx:${Libraries.Versions.androidCore_CoreKtx}"
    val org_jetbraings_kotlin_kotlin_bom = "org.jetbrains.kotlin:kotlin-bom:${Libraries.Versions.orgJetbrainsKotlin_KotlinBom}"
    val org_jetbrains_kotlinx_kotlinx_coroutines_test = "org.jetbrains.kotlinx:kotlinx-coroutines-test:${Libraries.Versions.orgJetbrainsKotlin_KotlinXCoroutuinesTest}"
    val androidx_appcompat_appcompat = "androidx.appcompat:appcompat:${Libraries.Versions.androidxAppcompatAppcompat}"
    val android_material = "com.google.android.material:material:${Libraries.Versions.androidMaterial}"
    val junit = "junit:junit:${Libraries.Versions.jUnit}"
    val androidx_test_ext_junit = "androidx.test.ext:junit:${Libraries.Versions.androidxTestExtJunit}"
    val androidx_test_espresso_espresso_core = "androidx.test.espresso:espresso-core:${Libraries.Versions.androidxTestEspressoEspressoCore}"
    val io_reactivex_rxjava3_rxjava = "io.reactivex.rxjava3:rxjava:${Libraries.Versions.rxjava3_version}"
    val io_reactivex_rxjava3_rxandroid = "io.reactivex.rxjava3:rxandroid:${Libraries.Versions.rxjava3_rxandroid_version}"
    val joda_time = "joda-time:joda-time:${Libraries.Versions.joda_date_time_version}"
    val io_mockk_mockk = "io.mockk:mockk:${Libraries.Versions.mockk_version}"
    val androidx_arch_core_core_testing = "androidx.arch.core:core-testing:${Libraries.Versions.androidxArchCore_CoreTesting}"
    val androidx_lifecycle_lifecycle_runtime_ktx = "androidx.lifecycle:lifecycle-runtime-ktx:${Libraries.Versions.androidxLifecycle_LifecycleRuntimeKtx}"
    val androidx_activity_activity_compose = "androidx.activity:activity-compose:${Libraries.Versions.androidxActivity_ActivityCompose}"
    val androidx_compose_compose_bom = "androidx.compose:compose-bom:${Libraries.Versions.androidxCompose_composeBOM}"
    //val androidx_compose_ui_ui_test_junit4 = 'androidx.compose.ui:ui-test-junit4'
    val androidx_compose_ui_ui = " androidx.compose.ui:ui"
    val androidx_compose_ui_ui_graphics = " androidx.compose.ui:ui-graphics"
    val androidx_compose_ui_ui_test_manifest = " androidx.compose.ui:ui-test-manifest"
    val androidx_compose_ui_ui_tooling_preview = " androidx.compose.ui:ui-tooling-preview"
    val androidx_compose_ui_ui_tooling = " androidx.compose.ui:ui-tooling"
    val androidx_compose_material3_material3 = " androidx.compose.material3:material3"
    val io_insert_koin_koin_android = "io.insert-koin:koin-android:${Libraries.Versions.ioInsertKoin_KoinAndroid}"
    val com_facebook_flipper_flipper = "com.facebook.flipper:flipper:${Libraries.Versions.comFacebookFlipper_Flipper}"
    val com_facebook_flipper_flipper_noop = "com.facebook.flipper:flipper-noop:${Libraries.Versions.comFacebookFlipper_Flipper}"
    val com_facebook_soloader_soloader = "com.facebook.soloader:soloader:${Libraries.Versions.comFacebookSOLoader_SOLoader}"
    val com_facebook_flipper_flipper_network_plugin = "com.facebook.flipper:flipper-network-plugin:${Libraries.Versions.comFacebookFlipper_Flipper}"
    val com_squareup_okhttp3_okhttp = "com.squareup.okhttp3:okhttp:${Libraries.Versions.okhttp_version}"
    val com_squareup_retrofit2_retrofit = "com.squareup.retrofit2:retrofit:${Libraries.Versions.retrofit_version}"
    val com_squareup_retrofit2_adapter_rxjava3 = "com.squareup.retrofit2:adapter-rxjava3:${Libraries.Versions.rxjava3_retrofitadapter_version}"
    val io_coil_kt_coil_compose = "io.coil-kt:coil-compose:${Libraries.Versions.ioCoilKt_CoilCompose}"
    val com_google_code_gson_gson = "com.google.code.gson:gson:${Libraries.Versions.comGoogleCodeGson_Gson}"
    val com_squareup_moshi_moshi_kotlin = "com.squareup.moshi:moshi-kotlin:${Libraries.Versions.comSquareupMoshi_MoshiKotlin}"
    val com_squareup_moshi_moshi_adapters = "com.squareup.moshi:moshi-adapters:${Libraries.Versions.comSquareupMoshi_MoshiAdapters}"
    val com_squareup_retrofit2_converter_moshi = "com.squareup.retrofit2:converter-moshi:${Libraries.Versions.comSquareupRetrofit2_ConverterMoshi}"
}